#!/bin/bash
SOURCE="$0"
while [ -h "$SOURCE"  ]; do
    DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd  )"
    SOURCE="$(readlink "$SOURCE")"
    [[ $SOURCE != /*  ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$( cd -P "$( dirname "$SOURCE"  )" && pwd  )"

COMPILE_DATE="`date +%Y.%m.%d`"
COMPILE_MARK=v$COMPILE_DATE
echo $COMPILE_MARK > $DIR/base-files/files/etc/buildmark
echo Compile mark set to $COMPILE_MARK
